Debug: add ls -R to 01-provision-infra

diff --git a/.github/workflows/01-provision-infra.yml b/.github/workflows/01-provision-infra.yml
--- a/.github/workflows/01-provision-infra.yml
+++ b/.github/workflows/01-provision-infra.yml
@@ -225,6 +225,13 @@ jobs:
     steps:
       - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
 
+      - name: Debug Checkout
+        run: |
+          echo "PWD: $(pwd)"
+          ls -la
+          echo "Vars Dir:"
+          ls -R vars || echo "vars directory not found"
+
       - name: Load Region from Config
         id: load-region
         run: |
